### ISSUE TITLE
build notifications are not sent after installing according to instructions in README

### ISSUE THREAD

**Issue by hardyoyo** [jcgay/maven-notifier#20]
Environment:

```
mvn --version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T19:39:06Z)
Maven home: /home/vagrant/.sdkman/candidates/maven/current
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-31-generic", arch: "amd64", family: "unix"
```
debug log:
https://gist.github.com/17d4fe2f4b824eaf24f8a27c917b0869

I've also tried this with the default version of Maven installed by Ubuntu 16.04:
```
mvn --version 
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-31-generic", arch: "amd64", family: "unix"
```
debug log:
https://gist.github.com/hardyoyo/b2ca6ade339d3f48d62bf29b3b942ae8

Any ideas?

**Comment by hardyoyo** [comment]
I've also confirmed notify-send is installed and working:

```
vagrant@dspace:~ |-/ which notify-send
/usr/bin/notify-send
vagrant@dspace:~ |-/ notify-send test
```

**Comment by jcgay** [comment]
I don't have the end of the logs but it seems that you have set `notifier.implementation` to `notify-send` instead of `notifysend`.  

Possible keys are listed here: https://github.com/jcgay/maven-notifier/wiki#configuration

I should probably log a warning when the chosen notifier doesn't exist...

**Comment by hardyoyo** [comment]
will try removing that, however, the wiki includes examples of both spellings (with and without a dash)

**Comment by hardyoyo** [comment]
The following seems to be working now:

```
notifier.implementation=notifysend
notifier.notify-send.path=/usr/bin/notify-send
```

I have this configuration in 3 places: $MAVEN_HOME/lib/ext/maven-notifier.properties, ~/.m2/maven-notifier.properties and .send-notification (all three of which are looked for and reported as missing during debug output, unless they are there...).

So... this issue is closeable, but the wiki might need some adjustments?

**Comment by hardyoyo** [comment]
Additional data point: the default Maven version 3.3.9 does not work, using the same configuration noted above. It would seem a newer version of Maven is required (3.5.0 worked for me, have the ability to change versions of Maven, would you like for me to step through a few releases to find the minimum version that works?

**Comment by hardyoyo** [comment]
I spoke too soon, I cannot duplicate the success from earlier, using the same configuration, for either Maven 3.5 or 3.3.9. Looking at the debug log, I think I see the issue:
```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:41 min
[INFO] Finished at: 2017-08-03T01:23:50+00:00
[INFO] Final Memory: 101M/287M
[INFO] ------------------------------------------------------------------------
[DEBUG] Will execute command line: /usr/bin/notify-send DSpace Parent Project Built in: 222 second(s). -i /tmp/send-notifications-icons/SUCCESS.png -u normal
```

in trying to run that command manually, I get the following error:

```
-bash: syntax error near unexpected token `('
```
it would seem we need to add some quotation marks to the notify-send message. I will see if I can make this modification myself. If I can figure it out, I'll make a PR.

**Comment by hardyoyo** [comment]
While looking into wrapping the build message with quotes (a trivial change) I noticed that the pom.xml limits this code to Java 1.6.... which has been EOL a while. I'm using Java 8. I'm wondering if I just need to give up on this and try something else?

**Comment by hardyoyo** [comment]
I managed to get maven-notifier to work, here's a pull request: https://github.com/jcgay/maven-notifier/pull/21 which addresses this issue.

**Comment by jcgay** [comment]
You can choose just one configuration file, the recommended one is `~/.m2/maven-notifier.properties`.

The output debug command is the array (concatenated with space) passed to `Runtime.getRuntime().exec()`. So it's not really executed in this form.

In the end, I have not been able to reproduce your error. I'm going to log extra informations to try to understand it.

This maven execution gives me a notification with notify-send:

```
$> mvn -X validate

Warning: JAVA_HOME environment variable is not set.
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_141, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.9.38-moby", arch: "amd64", family: "unix"
[DEBUG] Cannot read configuration at [file:/root/.send-notification], will use default one.
java.io.FileNotFoundException: /root/.send-notification (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1045)
	at fr.jcgay.notification.configuration.ConfigurationReader.atUrl(ConfigurationReader.java:40)
	at fr.jcgay.notification.configuration.ConfigurationReader.atPath(ConfigurationReader.java:30)
	at fr.jcgay.notification.SendNotification.<init>(SendNotification.java:55)
	at fr.jcgay.maven.notifier.sendnotification.SendNotificationNotifier.<init>(SendNotificationNotifier.java:36)
	at fr.jcgay.maven.notifier.sendnotification.SendNotificationNotifier$$FastClassByGuice$$598c0ad9.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:89)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:133)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:87)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:65)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:176)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:63)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
	at org.eclipse.sisu.wire.EntryListAdapter$ValueIterator.next(EntryListAdapter.java:111)
	at fr.jcgay.maven.notifier.NotificationEventSpyChooser.chooseNotifier(NotificationEventSpyChooser.java:61)
	at fr.jcgay.maven.notifier.NotificationEventSpyChooser.init(NotificationEventSpyChooser.java:28)
	at org.apache.maven.eventspy.internal.EventSpyDispatcher.init(EventSpyDispatcher.java:85)
	at org.apache.maven.cli.MavenCli.container(MavenCli.java:580)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:281)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[DEBUG] Global configuration is located at: file:/usr/share/maven/lib/ext/maven-notifier.properties
[DEBUG] User specific configuration is located at: file:////root/.m2/maven-notifier.properties
[DEBUG] Properties after loading [file:/usr/share/maven/lib/ext/maven-notifier.properties]: {notifier.implementation=notifysend, notifier.notify-send.path=/usr/bin/notify-send}
[DEBUG] Can't read file at [file:////root/.m2/maven-notifier.properties]. Skipping it...
java.io.FileNotFoundException: /root/.m2/maven-notifier.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1045)
	at fr.jcgay.maven.notifier.ConfigurationParser$ConfiguredProperties.load(ConfigurationParser.java:164)
	at fr.jcgay.maven.notifier.ConfigurationParser.readProperties(ConfigurationParser.java:49)
	at fr.jcgay.maven.notifier.ConfigurationParser.get(ConfigurationParser.java:39)
	at fr.jcgay.maven.notifier.ConfigurationParser.get(ConfigurationParser.java:35)
	at fr.jcgay.maven.notifier.AbstractCustomEventSpy.setConfiguration(AbstractCustomEventSpy.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.sisu.bean.BeanPropertySetter.set(BeanPropertySetter.java:76)
	at org.eclipse.sisu.plexus.ProvidedPropertyBinding.injectProperty(ProvidedPropertyBinding.java:48)
	at org.eclipse.sisu.bean.BeanInjector.injectMembers(BeanInjector.java:52)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:140)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:89)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:133)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:87)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:65)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:176)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:63)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
	at org.eclipse.sisu.wire.EntryListAdapter$ValueIterator.next(EntryListAdapter.java:111)
	at fr.jcgay.maven.notifier.NotificationEventSpyChooser.chooseNotifier(NotificationEventSpyChooser.java:61)
	at fr.jcgay.maven.notifier.NotificationEventSpyChooser.init(NotificationEventSpyChooser.java:28)
	at org.apache.maven.eventspy.internal.EventSpyDispatcher.init(EventSpyDispatcher.java:85)
	at org.apache.maven.cli.MavenCli.container(MavenCli.java:580)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:281)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[DEBUG] maven-notifier user configuration: Configuration{implementation=notifysend, shortDescription=true, threshold=-1, notifier-properties={notifier.implementation=notifysend, notifier.notify-send.path=/usr/bin/notify-send}}
[DEBUG] Will notify build success/failure with: fr.jcgay.maven.notifier.sendnotification.SendNotificationNotifier@a22cb6a
[DEBUG] Notification configuration read from file:/root/.send-notification is: {}.
[DEBUG] Overriding previous configuration with: {notifier.implementation=notifysend, notifier.notify-send.path=/usr/bin/notify-send}.
[DEBUG] Notifications will be send to: ChosenNotifiers{primary=notifysend, secondary=[]} for application: Application{id=application/x-vnd-apache.maven, name=Maven, timeout=-1, icon=Icon{id=maven, content=jar:file:/usr/share/maven/lib/ext/maven-notifier-1.10.2-SNAPSHOT-sources.jar!/maven.png}}.
[DEBUG] Configuring notify-send for application Application{id=application/x-vnd-apache.maven, name=Maven, timeout=-1, icon=Icon{id=maven, content=jar:file:/usr/share/maven/lib/ext/maven-notifier-1.10.2-SNAPSHOT-sources.jar!/maven.png}}: NotifySendConfiguration{bin=/usr/bin/notify-send}.
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: javax.enterprise.inject.* < plexus.core
[DEBUG]   Imported: javax.enterprise.util.* < plexus.core
[DEBUG]   Imported: javax.inject.* < plexus.core
[DEBUG]   Imported: org.apache.maven.* < plexus.core
[DEBUG]   Imported: org.apache.maven.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.classrealm < plexus.core
[DEBUG]   Imported: org.apache.maven.cli < plexus.core
[DEBUG]   Imported: org.apache.maven.configuration < plexus.core
[DEBUG]   Imported: org.apache.maven.exception < plexus.core
[DEBUG]   Imported: org.apache.maven.execution < plexus.core
[DEBUG]   Imported: org.apache.maven.execution.scope < plexus.core
[DEBUG]   Imported: org.apache.maven.lifecycle < plexus.core
[DEBUG]   Imported: org.apache.maven.model < plexus.core
[DEBUG]   Imported: org.apache.maven.monitor < plexus.core
[DEBUG]   Imported: org.apache.maven.plugin < plexus.core
[DEBUG]   Imported: org.apache.maven.profiles < plexus.core
[DEBUG]   Imported: org.apache.maven.project < plexus.core
[DEBUG]   Imported: org.apache.maven.reporting < plexus.core
[DEBUG]   Imported: org.apache.maven.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.rtinfo < plexus.core
[DEBUG]   Imported: org.apache.maven.settings < plexus.core
[DEBUG]   Imported: org.apache.maven.toolchain < plexus.core
[DEBUG]   Imported: org.apache.maven.usability < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.* < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authentication < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authorization < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.events < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.observers < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.proxy < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.resource < plexus.core
[DEBUG]   Imported: org.codehaus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.* < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.component < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.configuration < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.container < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.context < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.logging < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.personality < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.* < plexus.core
[DEBUG]   Imported: org.eclipse.aether.artifact < plexus.core
[DEBUG]   Imported: org.eclipse.aether.collection < plexus.core
[DEBUG]   Imported: org.eclipse.aether.deployment < plexus.core
[DEBUG]   Imported: org.eclipse.aether.graph < plexus.core
[DEBUG]   Imported: org.eclipse.aether.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.installation < plexus.core
[DEBUG]   Imported: org.eclipse.aether.internal.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.metadata < plexus.core
[DEBUG]   Imported: org.eclipse.aether.repository < plexus.core
[DEBUG]   Imported: org.eclipse.aether.resolution < plexus.core
[DEBUG]   Imported: org.eclipse.aether.spi < plexus.core
[DEBUG]   Imported: org.eclipse.aether.transfer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.version < plexus.core
[DEBUG]   Imported: org.slf4j.* < plexus.core
[DEBUG]   Imported: org.slf4j.helpers.* < plexus.core
[DEBUG]   Imported: org.slf4j.spi.* < plexus.core
[DEBUG] Populating class realm maven.api
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/share/maven/conf/settings.xml
[DEBUG] Reading user settings from /root/.m2/settings.xml
[DEBUG] Reading global toolchains from /usr/share/maven/conf/toolchains.xml
[DEBUG] Reading user toolchains from /root/.m2/toolchains.xml
[DEBUG] Using local repository at /root/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for /root/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project test:test-name:jar:1.0-SNAPSHOT: (none)
[DEBUG] Looking up lifecyle mappings for packaging jar from ClassRealm[plexus.core, parent: null]
[DEBUG] === REACTOR BUILD PLAN ================================================
[DEBUG] Project: test:test-name:jar:1.0-SNAPSHOT
[DEBUG] Tasks:   [validate]
[DEBUG] Style:   Regular
[DEBUG] =======================================================================
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building test name with space 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] === PROJECT BUILD PLAN ================================================
[DEBUG] Project:       test:test-name:1.0-SNAPSHOT
[DEBUG] Dependencies (collect): []
[DEBUG] Dependencies (resolve): []
[DEBUG] Repositories (dependencies): [central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] Repositories (plugins)     : [central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] =======================================================================
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.135 s
[INFO] Finished at: 2017-08-15T17:50:43+00:00
[INFO] Final Memory: 11M/94M
[INFO] ------------------------------------------------------------------------
[DEBUG] Will execute command line: /usr/bin/notify-send test name with space Built in: 0 second(s). -i /tmp/send-notifications-icons/SUCCESS.png -u normal
```

**Comment by jcgay** [comment]
I've added logs to get the return code of `notify-send`: https://oss.sonatype.org/content/repositories/snapshots/fr/jcgay/maven/maven-notifier/1.10.2-SNAPSHOT/maven-notifier-1.10.2-20170816.170759-3.zip

Could you give it a try and paste the debug log here ?

Thanks!

**Comment by jcgay** [comment]
Feel free to re-open if it's still actual.
